Dev
ClevertecFrontendLab/artemshaf pull request #1
Opened 2023-02-12 11:04 UTC by artemshaf

2023-02-12 11:08 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200098/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200098/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200098/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200098/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200098/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200098/main-loading.png)

2023-02-12 11:13 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200421/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200421/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200421/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200421/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200421/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200421/main-loading.png)

2023-02-12 11:21 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200863/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200863/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200863/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200863/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200863/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676200863/main-loading.png)

2023-02-12 11:24 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201096/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201096/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201096/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201096/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201096/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201096/main-loading.png)

2023-02-12 11:30 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 4.
Количество непройденных тестов: 2.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201446/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**Get books test -- getSuccessBookId -- bookId-success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201446/Get%20books%20test%20--%20getSuccessBookId%20--%20bookId-success%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201446/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201446/bookId-loading.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201446/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201446/main-loading.png)

2023-02-12 11:37 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201864/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201864/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201864/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201864/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201864/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676201864/main-loading.png)

2023-02-12 11:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676202432/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676202432/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676202432/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676202432/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676202432/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676202432/main-loading.png)

2023-02-12 12:19 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676204395/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676204395/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676204395/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676204395/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676204395/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676204395/main-loading.png)

2023-02-12 14:14 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676211289/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676211289/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676211289/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676211289/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676211289/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676211289/main-loading.png)

2023-02-12 14:42 UTC, vvikota commented
![image](https://user-images.githubusercontent.com/30027067/218317726-8bd81e82-2620-4b11-9963-2fba3bb8c24c.png)
колличество книг не по макету, нужен отступ и другой шрифт

2023-02-12 14:43 UTC, vvikota commented
![image](https://user-images.githubusercontent.com/30027067/218317774-c57ebf65-6609-4a6a-b60d-24eba1b5ff64.png)
элемент не по макету, не хватает закругления углов и текст неверный

2023-02-12 14:44 UTC, vvikota commented
![image](https://user-images.githubusercontent.com/30027067/218317827-0ca1968f-0e3a-4f7b-a090-921492419bd9.png)
когда страница книги открыта то тут указываем текущую категорию

2023-02-12 14:48 UTC, vvikota commented
![image](https://user-images.githubusercontent.com/30027067/218318038-4d08677e-6051-4adf-b7b9-ee633061b7f0.png)
при отображении ошибки, тут не хватает бокового меню, так же на детальной страницы книги при отображении ошибки должна быть видна пагинация

2023-02-13 12:23 UTC, vvikota requested changes

2023-02-13 12:23 UTC, vvikota commented on .editorconfig
> +
нужны исправления, смотри скрины

2023-02-14 03:40 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346017/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346017/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346017/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346017/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346017/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346017/main-loading.png)

2023-02-14 03:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346384/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346384/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346384/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346384/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346384/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346384/main-loading.png)

2023-02-14 03:49 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346554/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346554/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346554/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346554/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346554/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676346554/main-loading.png)

2023-02-14 06:06 UTC, vvikota commented
![image](https://user-images.githubusercontent.com/30027067/218653314-4a7ddf8f-f9e5-46b9-b12b-915ee93b8950.png)
для этого пункта не нужно указывать количество

2023-02-14 06:29 UTC, vvikota requested changes

2023-02-14 06:29 UTC, vvikota commented on src/app/components/business/book-list/book-item/book-item.tsx
> +export const BookItem = memo(({ book, variantDisplay = 'list', className, ...props }: IBookItemInterface) => {
тут надо разбить на два компонента

2023-02-14 06:29 UTC, vvikota commented on src/app/components/business/book/book-info/book-info.tsx
> +          <Typography variant='span'>Питер</Typography>
тут и ниже эти значения получаем уже с сервера, нужно заменить

2023-02-14 06:29 UTC, vvikota commented on src/app/components/business/calendar/calendar.tsx
> +  useEffect(() => {
если это не нужно то удалить

2023-02-14 06:29 UTC, vvikota commented on src/app/components/business/book-list/book-item/book-item.tsx
> +              <Rating isChanged={false} rate={3} className={classNames(styles.rating)} />
почему rate={3}? Это значение уже приходит с серрвера

2023-02-14 06:29 UTC, vvikota commented on src/app/data/books.ts
> +// export interface IBook {
удалить

2023-02-14 08:57 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 4.
Количество непройденных тестов: 2.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365033/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**Get books test -- getSuccessBookId -- bookId-success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365033/Get%20books%20test%20--%20getSuccessBookId%20--%20bookId-success%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365033/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365033/bookId-loading.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365033/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365033/main-loading.png)

2023-02-14 09:00 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 4.
Количество непройденных тестов: 2.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365242/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**Get books test -- getSuccessBookId -- bookId-success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365242/Get%20books%20test%20--%20getSuccessBookId%20--%20bookId-success%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365242/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365242/bookId-loading.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365242/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365242/main-loading.png)

2023-02-14 09:11 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 4.
Количество непройденных тестов: 2.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365861/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**Get books test -- getSuccessBookId -- bookId-success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365861/Get%20books%20test%20--%20getSuccessBookId%20--%20bookId-success%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365861/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365861/bookId-loading.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365861/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676365861/main-loading.png)

2023-02-14 09:19 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 4.
Количество непройденных тестов: 2.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366365/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**Get books test -- getSuccessBookId -- bookId-success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366365/Get%20books%20test%20--%20getSuccessBookId%20--%20bookId-success%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366365/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366365/bookId-loading.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366365/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366365/main-loading.png)

2023-02-14 09:22 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366532/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366532/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366532/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366532/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366532/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366532/main-loading.png)

2023-02-14 09:25 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 4.
Количество непройденных тестов: 2.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366749/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**Get books test -- getSuccessBookId -- bookId-success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366749/Get%20books%20test%20--%20getSuccessBookId%20--%20bookId-success%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366749/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366749/bookId-loading.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366749/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676366749/main-loading.png)

2023-02-14 10:24 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 4.
Количество непройденных тестов: 2.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676370264/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**Get books test -- getSuccessBookId -- bookId-success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676370264/Get%20books%20test%20--%20getSuccessBookId%20--%20bookId-success%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676370264/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676370264/bookId-loading.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676370264/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676370264/main-loading.png)

2023-02-14 11:32 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676374323/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676374323/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676374323/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676374323/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676374323/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676374323/main-loading.png)

2023-02-14 11:37 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676374660/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676374660/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676374660/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676374660/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676374660/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676374660/main-loading.png)

2023-02-14 11:43 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 4.
Количество непройденных тестов: 2.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676375028/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**Get books test -- getSuccessBookId -- bookId-success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676375028/Get%20books%20test%20--%20getSuccessBookId%20--%20bookId-success%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676375028/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676375028/bookId-loading.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676375028/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676375028/main-loading.png)

2023-02-14 12:06 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676376382/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676376382/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676376382/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676376382/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676376382/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676376382/main-loading.png)

2023-02-14 12:37 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676378237/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676378237/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676378237/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676378237/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676378237/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676378237/main-loading.png)

2023-02-14 15:12 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 4.
Количество непройденных тестов: 1.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676387576/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676387576/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676387576/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676387576/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676387576/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676387576/main-loading.png)

2023-02-14 15:25 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 50%.
Общее количество тестов: 4.
Количество непройденных тестов: 2.
***
**Get books test -- getCategoriesAndBooks -- categories-loading (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676388316/Get%20books%20test%20--%20getCategoriesAndBooks%20--%20categories-loading%20(failed).png)
***
**Get books test -- getSuccessBookId -- bookId-success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676388316/Get%20books%20test%20--%20getSuccessBookId%20--%20bookId-success%20(failed).png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676388316/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676388316/bookId-loading.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676388316/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676388316/main-loading.png)

2023-02-14 15:33 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**app-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676388817/app-sucess.png)
***
**bookId-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676388817/bookId-error.png)
***
**bookId-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676388817/bookId-loading.png)
***
**bookId-sucess.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676388817/bookId-sucess.png)
***
**categories-error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676388817/categories-error.png)
***
**main-loading.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1676388817/main-loading.png)

2023-02-14 15:45 UTC, vvikota approved these changes

2023-02-14 15:49 UTC, merged